/**
 * Agent Plugin System — Production Grade
 * 
 * Allows agents to register capabilities, hooks, and extensions
 * that integrate with the registry and federation.
 */

class AgentPlugin {
    constructor(name, version = '1.0.0') {
        this.name = name;
        this.version = version;
        this.hooks = new Map();
        this.capabilities = new Set();
        this.registry = null;
    }

    /**
     * Install plugin into registry
     */
    install(registry) {
        this.registry = registry;
        this.registerHooks();
        this.registerCapabilities();
        console.log(`[Plugin] ${this.name} v${this.version} installed`);
    }

    /**
     * Uninstall plugin
     */
    uninstall() {
        this.hooks.clear();
        this.capabilities.clear();
        this.registry = null;
        console.log(`[Plugin] ${this.name} uninstalled`);
    }

    /**
     * Override to register hooks
     */
    registerHooks() {}

    /**
     * Override to register capabilities
     */
    registerCapabilities() {}

    /**
     * Register a hook
     */
    hook(event, handler, priority = 0) {
        if (!this.hooks.has(event)) {
            this.hooks.set(event, []);
        }
        this.hooks.get(event).push({ handler, priority, plugin: this.name });
        this.hooks.get(event).sort((a, b) => b.priority - a.priority);
    }

    /**
     * Execute hooks for event
     */
    async executeHooks(event, data) {
        const hooks = this.hooks.get(event) || [];
        for (const { handler, plugin } of hooks) {
            try {
                await handler(data, this.registry);
            } catch (error) {
                console.error(`[Plugin:${plugin}] Hook ${event} failed:`, error);
            }
        }
    }

    /**
     * Add capability
     */
    addCapability(capability) {
        this.capabilities.add(capability);
        if (this.registry) {
            this.registry.emit('capabilityRegistered', { plugin: this.name, capability });
        }
    }

    /**
     * Check if plugin has capability
     */
    hasCapability(capability) {
        return this.capabilities.has(capability);
    }
}

/**
 * Built-in plugins
 */

// Avatar Generation Plugin
class AvatarPlugin extends AgentPlugin {
    constructor() {
        super('avatar-generation', '1.0.0');
    }

    registerCapabilities() {
        this.addCapability('avatar:generate');
        this.addCapability('avatar:fallback');
        this.addCapability('avatar:identicon');
        this.addCapability('avatar:svg');
    }

    registerHooks() {
        this.hook('agent:register', async (data) => {
            if (data.agent && !data.agent.avatar) {
                // Avatar will be generated by registry
            }
        }, 10);
    }
}

// Room Management Plugin
class RoomPlugin extends AgentPlugin {
    constructor() {
        super('room-management', '1.0.0');
    }

    registerCapabilities() {
        this.addCapability('room:assign');
        this.addCapability('room:rebalance');
        this.addCapability('room:overflow');
    }

    registerHooks() {
        this.hook('room:created', async (data) => {
            console.log(`[RoomPlugin] New production room created: ${data.room.id}`);
        });
    }
}

// Federation Sync Plugin
class FederationPlugin extends AgentPlugin {
    constructor() {
        super('federation-sync', '1.0.0');
    }

    registerCapabilities() {
        this.addCapability('federation:register');
        this.addCapability('federation:sync');
        this.addCapability('federation:heartbeat');
    }

    registerHooks() {
        this.hook('agent:register', async (data) => {
            if (data.agent && this.registry) {
                await this.registry.registerWithFederation(data.agent);
            }
        }, 5);

        this.hook('agent:remove', async (data) => {
            if (this.registry) {
                try {
                    await fetch(`${this.registry.config.federationUrl}/api/leave`, {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify({ agentId: data.agentId, projectId: this.registry.config.projectId })
                    });
                } catch (e) { /* ignore */ }
            }
        });
    }
}

// Health Monitoring Plugin
class HealthPlugin extends AgentPlugin {
    constructor() {
        super('health-monitoring', '1.0.0');
    }

    registerCapabilities() {
        this.addCapability('health:check');
        this.addCapability('health:report');
        this.addCapability('health:alert');
    }

    registerHooks() {
        this.hook('health:check', async (data) => {
            // Custom health checks per agent type
        });

        this.hook('agent:degraded', async (data) => {
            console.warn(`[HealthPlugin] Agent degraded: ${data.agentId}`);
            // Could trigger alerts, auto-restart, etc.
        });
    }
}

// TV Room Integration Plugin
class TVRoomPlugin extends AgentPlugin {
    constructor() {
        super('tv-room-integration', '1.0.0');
    }

    registerCapabilities() {
        this.addCapability('tv:render');
        this.addCapability('tv:feed');
        this.addCapability('tv:status');
    }

    registerHooks() {
        this.hook('agent:register', async (data) => {
            // Auto-update TV room display
            if (typeof window !== 'undefined' && window.updateTVRoom) {
                window.updateTVRoom(data.agent);
            }
        });

        this.hook('agent:statusChange', async (data) => {
            if (typeof window !== 'undefined' && window.updateAgentStatus) {
                window.updateAgentStatus(data.agentId, data.status);
            }
        });
    }
}

// Plugin Manager
class PluginManager {
    constructor(registry) {
        this.registry = registry;
        this.plugins = new Map();
        this.loadOrder = [];
    }

    /**
     * Load built-in plugins
     */
    loadBuiltins() {
        const builtins = [
            new AvatarPlugin(),
            new RoomPlugin(),
            new FederationPlugin(),
            new HealthPlugin(),
            new TVRoomPlugin()
        ];

        builtins.forEach(plugin => this.loadPlugin(plugin));
    }

    /**
     * Load a plugin
     */
    loadPlugin(plugin) {
        if (this.plugins.has(plugin.name)) {
            console.warn(`[PluginManager] Plugin ${plugin.name} already loaded`);
            return false;
        }

        try {
            plugin.install(this.registry);
            this.plugins.set(plugin.name, plugin);
            this.loadOrder.push(plugin.name);
            return true;
        } catch (error) {
            console.error(`[PluginManager] Failed to load ${plugin.name}:`, error);
            return false;
        }
    }

    /**
     * Load plugin from file/module
     */
    async loadPluginFromModule(modulePath) {
        try {
            const module = await import(modulePath);
            const PluginClass = module.default || module.Plugin || module[Object.keys(module)[0]];
            if (PluginClass && PluginClass.prototype instanceof AgentPlugin) {
                return this.loadPlugin(new PluginClass());
            }
            throw new Error('Invalid plugin module');
        } catch (error) {
            console.error(`[PluginManager] Failed to load from ${modulePath}:`, error);
            return false;
        }
    }

    /**
     * Unload plugin
     */
    unloadPlugin(name) {
        const plugin = this.plugins.get(name);
        if (plugin) {
            plugin.uninstall();
            this.plugins.delete(name);
            this.loadOrder = this.loadOrder.filter(n => n !== name);
            return true;
        }
        return false;
    }

    /**
     * Get plugin
     */
    getPlugin(name) {
        return this.plugins.get(name);
    }

    /**
     * Get all plugins
     */
    getAllPlugins() {
        return Array.from(this.plugins.values());
    }

    /**
     * Get plugins with capability
     */
    getPluginsWithCapability(capability) {
        return this.getAllPlugins().filter(p => p.hasCapability(capability));
    }

    /**
     * Execute hooks across all plugins
     */
    async executeHooks(event, data) {
        for (const plugin of this.plugins.values()) {
            await plugin.executeHooks(event, data);
        }
    }
}

// Export
export {
    AgentPlugin,
    PluginManager,
    AvatarPlugin,
    RoomPlugin,
    FederationPlugin,
    HealthPlugin,
    TVRoomPlugin
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        AgentPlugin,
        PluginManager,
        AvatarPlugin,
        RoomPlugin,
        FederationPlugin,
        HealthPlugin,
        TVRoomPlugin
    };
}
if (typeof window !== 'undefined') {
    window.AgentPlugin = AgentPlugin;
    window.PluginManager = PluginManager;
    window.AvatarPlugin = AvatarPlugin;
    window.RoomPlugin = RoomPlugin;
    window.FederationPlugin = FederationPlugin;
    window.HealthPlugin = HealthPlugin;
    window.TVRoomPlugin = TVRoomPlugin;
}